import MainLayout from "@/component/MainLayout";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";

const notoSans = localFont({
  src: "../../public/fonts/NotoSans/NotoSans-vf.woff",
  variable: "--font-noto-sans",
  weight: "100 900",
  display: "block",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${notoSans.variable}`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
