// types
import type { Metadata, Viewport } from 'next';

// next
import Script from 'next/script';

// layout
import MainLayout from '@/component/layout/MainLayout';

// style & font
import '@/styles/globals.scss';
import { pretendard } from '@/app/fonts';

// providers
import AOSProvider from '@/app/providers/AOSProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  // 오픈그래프 추가
  openGraph: {
    title: '오픈그래프 제목',
    description: '오픈그래프 설명',
    url: 'https://react-portfolio-iota-ten-41.vercel.app',
    siteName: '사이트 이름',
    images: [
      {
        url: 'https://github.com/9Gu-Mo/React_Portfolio/blob/c2cae50f17186e01dcb43d6ddee5d8b033daba69/public/images/bg/bg2.jpg',
        width: 1920,
        height: 1080,
        alt: '배경 이미지',
      },
    ],
    locale: 'ko_KR',
    type: 'website',
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1.0,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      suppressHydrationWarning
      className={`${pretendard.className} overflow-x-hidden`}
    >
      <head>
        <Script
          id="scroll-reset"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                if ('scrollRestoration' in history) {
                  history.scrollRestoration = 'manual';
                }
                window.scrollTo(0, 0);
                
                // 해시가 있어도 스크롤 방지
                if (window.location.hash) {
                  history.replaceState(null, '', window.location.pathname + window.location.search);

                  setTimeout(function() {
                    window.scrollTo(0, 0);
                  }, 0);
                }
              })();
            `,
          }}
        />
      </head>
      <body>
        <AOSProvider>
          <MainLayout>{children}</MainLayout>
        </AOSProvider>
      </body>
    </html>
  );
}
